### DISCUSSION TITLE
Docker?

### DISCUSSION THREAD

**Discussion by yglodt** [monarc-project/MonarcAppFO#454] [Q&A]
Hello,

Is there a reason that installing Monarc in Docker is not documented ? Is this supported, or encouraged generally?

Thanks and best regards

**Comment by ruslanbaidan** [comment]
Hello,

Monarc is an open source project and free to use.
We got [some contribution](https://github.com/prouveyrol/Monarc-Docker/blob/main/Dockerfile), but did not have time to review if it works.
Any suggestions, improvements and contributions are always welcome.

Thank you.

**Comment by yglodt** [comment]
Hello,

thank you for pointing to the contributed Dockerfile. It looks like it does the job.

I'll take a look at it and share back any findings I may have.

Best regards.

**Reply by ghost** [reply]
Hello,

using the suggested Dockerfile we created the following docker-compose.yml
We  successfully established the database connection. Also the monarc login page would  presented. Adminer is working too.
The trouble starts when we try to login with the default monarc credentials. The app refuse to accept those credentials. Even after we imported two well working instances of monarc_common and monarc_cli were  via mysql, the credentials of the stored users would not allow to enter he app. 
Could it be an issue with the hashing algorithm in monarc_cli.users ?  Which one is the correct hash of the default 'admin'-password?
Or do you have any other idea ?

Thanks


```
# content of /home/user/monarc/docker-compose.yml

version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes:
    - '/home/user/monarc/mariadb/:/var/lib/mysql/'

    environment:
      MARIADB_ROOT_PASSWORD: example

  monarc:
    build:
      context: ./monarc-docker     
      dockerfile: Dockerfile    # source: https://github.com/prouveyrol/Monarc-Docker/blob/main/Dockerfile
    restart: always
    environment:
      db_host: mariadb 
      db_common_name: monarc_common 
      db_cli_name: monarc_cli
      db_user: monarc 
      db_pass: example
    ports:
      - 8080:80


  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    ```
