### DISCUSSION TITLE
Containerization

### DISCUSSION THREAD

**Discussion by yentl-creyf** [monarc-project/MonarcAppFO#480] [Ideas]
Hey, 

we tried to get the project up and running locally, there were some challenges with it.

I think the experience for running (but also contributing, testing, maintaining)  the project, would be a lot better if it were containerized.

Here is an example folder structure:
- MonarcAppFO

Here you should have one docker-compose.yml file to create the database & php

- MonarcAppFO/database

documentation: https://hub.docker.com/_/mysql

file: DockerFile
```Docker
FROM mysql:latest

EXPOSE 3306
```
file: docker-compose.yml
```yml
version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monarc-db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_for_development
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mount:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
```
- MonarcAppFO/database/docker-entrypoint-initdb.d

here goes your .sql files that will initiate your database

- MonarcAppFO/front_end

from the documentation: https://hub.docker.com/_/php

you can use: php:<version>-apache

This image contains Debian's Apache httpd in conjunction with PHP (as mod_php) and uses mpm_prefork by default.

Apache with a Dockerfile
```Docker
FROM php:7.2-apache
COPY src/ /var/www/html/
````
Where src/ is the directory containing all your PHP code. Then, run the commands to build and run the Docker image:

```
$ docker build -t my-php-app .
$ docker run -d --name my-running-app my-php-app
```
We recommend that you add a php.ini configuration file; see the "Configuration" section for details.

same goes for your python & postgress components
- https://hub.docker.com/_/python
    - i would suggest `python:<version>-slim`
- https://hub.docker.com/_/postgres
