### ISSUE TITLE
Console error after login (TypeError: Cannot read properties of undefined (reading '1'))

### ISSUE THREAD

**Issue by ghost** [monarc-project/MonarcAppFO#530]
**Describe the bug**
Fresh install for Monarc. I am using Docker & MySQL. I have created and seeded both databases as well as the initial user. When trying to log in, The auth request is accepted but the frontend has a error in the console preventing from site to actually log me in:
TypeError: Cannot read properties of undefined (reading '1')

Have I skipped a step? Thanks.

**To Reproduce**
1. Log in
2. See error

**Expected behavior**
Redirect to home page after login.

**Desktop:**
| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu
| OS version (client)                   | Windows 11
| PHP version                             | 8.0
| MONARC version / git hash     | 036cd44
| Browser                                    | Chrome

**Comment by JoachimVeulemansSecuRoad** [comment]
Build image with this Dockerfile: https://github.com/prouveyrol/Monarc-Docker/blob/main/Dockerfile. I have replaced the PHP version with 8.0-apache.

Execute SQL: https://github.com/monarc-project/MonarcAppFO/blob/master/db-bootstrap/monarc_structure.sql
Execute SQL: https://github.com/monarc-project/MonarcAppFO/blob/master/db-bootstrap/monarc_data.sql

Create docker-compose.yml with:
```
version: '3.1'

services:
  monarc:
    build:
      context: .
      dockerfile: Dockerfile    # source: https://github.com/prouveyrol/Monarc-Docker/blob/main/Dockerfile
    restart: always
    environment:
      db_host: IP
      db_common_name: monarc_common
      db_cli_name: monarc_cli
      db_user: monarc
      db_pass: PW
    ports:
      - 3008:80
```

Run docker container
Execute in container:
```
php ./vendor/robmorgan/phinx/bin/phinx migrate -c module/Monarc/FrontOffice/migrations/phinx.php
php ./vendor/robmorgan/phinx/bin/phinx migrate -c module/Monarc/Core/migrations/phinx.php
php ./vendor/robmorgan/phinx/bin/phinx seed:run -c ./module/Monarc/FrontOffice/migrations/phinx.php
```

Login with admin@admin.localhost and admin.

See request response:
![image](https://github.com/monarc-project/MonarcAppFO/assets/130068042/b3676f98-51fa-4e8d-917e-1af6a3bf5e47)

See errors:
![image](https://github.com/monarc-project/MonarcAppFO/assets/130068042/d35a2fc2-6851-4525-9d60-93a342bc15e0)

I have tried other languages ids like 0 and 2 but no success.

Thanks.
